'use strict';

/** Phone Numbers (DIDs) — Espresso DID V3 SOAP, one REST endpoint per method. */

module.exports = [
  {
    method: 'GET', path: '/api/ping', soap: 'testConnection',
    summary: 'Health & auth check',
    description: 'Confirms the gateway is up and your Espresso credentials are accepted. Use this first when setting up.',
    params: [{ name: 'name', in: 'query', required: false, description: 'Any label; echoed back in the response.' }],
    returns: 'The greeting string from Espresso and the authenticated username.',
    errors: [{ code: 1, when: 'No credentials sent.' }, { code: 2, when: 'Wrong username / password.' }],
  },
  {
    method: 'GET', path: '/api/catalog', soap: 'didGetProductCatalog',
    summary: 'List available rate centers / NPAs',
    description: 'Returns every rate center + NPA (area code) pair you are allowed to order DIDs from. Use these exact values when creating an order — a mismatch is rejected (595 / 596).',
    returns: 'Array of { ratecenter, npa } entries.',
    errors: [{ code: 431, when: 'Product catalog is empty for your account.' }],
  },
  {
    method: 'GET', path: '/api/routing-profiles', soap: 'didGetRoutingProfiles',
    summary: 'List routing profiles',
    description: 'Returns your routing profiles. When you place an order you must pass the profile name in the EXACT form returned here.',
    returns: 'Array of profile identifiers/names.',
    errors: [{ code: 451, when: 'No routing profiles assigned to your account.' }],
  },
  {
    method: 'GET', path: '/api/routing-profiles/full', soap: 'didGetRoutingProfilesDetailsFull',
    summary: 'List routing profiles (full detail)',
    description: 'Like /routing-profiles but each profile also includes tech_prefix and format (E164 or National). These replace the deprecated prefix / country_prefix request fields.',
    returns: 'Array of profiles with tech_prefix and format.',
  },
  {
    method: 'GET', path: '/api/routing-profiles/:profile', soap: 'didGetRoutingProfileDetails',
    summary: 'Get one routing profile',
    description: 'Full details for a single profile. URL-encode the value (e.g. "Profile 2542" -> "Profile%202542"). The profile must match the form from /routing-profiles.',
    params: [{ name: 'profile', in: 'path', required: true, description: 'Profile name/number, exactly as returned by /routing-profiles.' }],
    errors: [{ code: 472, when: 'Profile does not exist or is not yours.' }],
  },
  {
    method: 'POST', path: '/api/orders', soap: 'didOrderDids',
    summary: 'Create a DID order',
    description: 'Places a new order. Requests are grouped by routing profile. Each request asks for a quantity of DIDs in a given rate center + NPA. prefix / country_prefix are deprecated and ignored — safe to omit.',
    body: {
      profiles: [{
        profile: 'Profile 2542',
        requests: [{ ratecenter: 'TORONTO', npa: '647', quantity: 1 }],
      }],
    },
    fields: [
      { name: 'profiles[].profile', required: true, description: 'Profile name, exact form from /routing-profiles.' },
      { name: 'requests[].ratecenter', required: true, description: 'Rate center from /catalog.' },
      { name: 'requests[].npa', required: true, description: 'NPA (area code) valid for that rate center.' },
      { name: 'requests[].quantity', required: true, description: 'How many DIDs (integer > 0).' },
    ],
    returns: 'The created order (order number + initial status). Poll /status afterward.',
    errors: [
      { code: 594, when: 'Quantity must be greater than 0.' },
      { code: 595, when: 'Rate center is not valid (see /catalog).' },
      { code: 596, when: 'NPA not valid for that rate center.' },
      { code: 592, when: 'Requested DIDs exceed your daily quota.' },
    ],
  },
  {
    method: 'GET', path: '/api/orders', soap: 'didGetOrders',
    summary: 'List orders in a date range',
    description: 'All orders your company created between two timestamps.',
    params: [
      { name: 'from', in: 'query', required: true, description: 'Start datetime, format "Y-m-d H:i:s" e.g. 2026-08-01 00:00:00.' },
      { name: 'to', in: 'query', required: true, description: 'End datetime, same format.' },
    ],
    returns: 'Array of orders with their statuses.',
  },
  {
    method: 'GET', path: '/api/orders/:id', soap: 'didGetOrderInfo',
    summary: 'Get order info',
    description: 'The profile + requests that make up an order. The shape changes after you edit an order or discard rejected requests.',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number, e.g. DID1205280200006.' }],
    errors: [{ code: 511, when: 'Order id does not exist.' }],
  },
  {
    method: 'GET', path: '/api/orders/:id/status', soap: 'didGetOrderStatus',
    summary: 'Get order status',
    description: 'Current status. Poll this after creating or editing an order.',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    returns: 'One of: Processing, Approved, Completed, Rejected. Pending Update, Rejected, Canceled.',
  },
  {
    method: 'GET', path: '/api/orders/:id/details', soap: 'didGetOrderDetails',
    summary: 'List provisioned DIDs',
    description: 'The actual DID numbers assigned to the order.',
    precondition: 'Order status must be "Completed".',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    errors: [{ code: 531, when: 'Order is not "Completed" (409). Check /status.' }],
  },
  {
    method: 'GET', path: '/api/orders/:id/problems', soap: 'didGetOrderProblems',
    summary: 'List rejected requests',
    description: 'The rejected requests in an order and why each was rejected.',
    precondition: 'Order status must be "Rejected. Pending Update".',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    errors: [{ code: 551, when: 'Order is not "Rejected. Pending Update" (409).' }],
  },
  {
    method: 'POST', path: '/api/orders/:id/requests', soap: 'didOrderEdit',
    summary: 'Append requests to an order',
    description: 'Adds more DID requests to an order that was partly rejected. Requests are APPENDED to the accepted ones — this does not replace anything.',
    precondition: 'Order status must be "Rejected. Pending Update".',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    body: { requests: [{ ratecenter: 'PARRY SOUND', npa: '705', quantity: 3 }] },
    fields: [
      { name: 'requests[].ratecenter', required: true, description: 'Rate center from /catalog.' },
      { name: 'requests[].npa', required: true, description: 'NPA valid for that rate center.' },
      { name: 'requests[].quantity', required: true, description: 'How many DIDs (integer > 0).' },
    ],
    errors: [{ code: 551, when: 'Order is not "Rejected. Pending Update" (409).' }],
  },
  {
    method: 'POST', path: '/api/orders/:id/discard-rejected', soap: 'didOrderDiscardRejected',
    summary: 'Discard rejected requests',
    description: 'Drops all rejected requests, keeping only the accepted ones, so the order can proceed.',
    precondition: 'Status "Rejected. Pending Update" AND at least one accepted request must remain.',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    errors: [{ code: 551, when: 'Order is not in the right state, or nothing accepted remains (409).' }],
  },
  {
    method: 'POST', path: '/api/orders/:id/cancel', soap: 'didOrderCancel',
    summary: 'Cancel an order',
    description: 'Cancels the whole order.',
    precondition: 'Order status must be "Rejected. Pending Update".',
    params: [{ name: 'id', in: 'path', required: true, description: 'Order number.' }],
    errors: [{ code: 551, when: 'Order is not "Rejected. Pending Update" (409).' }],
  },
];
