'use strict';

/**
 * Hand-authored "how do I actually use this" diagrams, one per product.
 *
 * These live here rather than in lib/catalogs/iristelx/*.json because those
 * files are regenerated by scripts/import-iristelx.js — anything written there
 * would be destroyed on the next import.
 *
 * Shape:
 *   title     headline above the diagram
 *   subtitle  one line explaining what the flow accomplishes
 *   steps[]   { title, text, tone, detail:{ endpoint, rows:[[label, value]] } }
 *             tone: blue | green | purple | amber | teal | red  (step accent)
 *   notes[]   bullet points rendered under the diagram
 *
 * The console renders these as HTML/CSS — no image files, so they stay
 * readable in the dark theme, reflow on mobile and remain searchable.
 */

const FLOWS = {
  dids: {
    title: 'Ordering DIDs end to end',
    subtitle: 'Confirm what you may order, place the order, then collect the numbers.',
    steps: [
      {
        title: 'Check credentials', tone: 'blue',
        text: 'Confirm the gateway is up and your Espresso login is accepted before anything else.',
        detail: { endpoint: 'GET /api/ping', rows: [['Response', '{ result: "Hello …" }']] },
      },
      {
        title: 'Read the catalog', tone: 'green',
        text: 'Get the rate centers and NPAs you are allowed to order from. Use these values verbatim.',
        detail: { endpoint: 'GET /api/catalog', rows: [['Response', '{ items: [{ ratecenter, npa }] }']] },
      },
      {
        title: 'Pick a routing profile', tone: 'purple',
        text: 'Orders are grouped by routing profile. Pass the profile name exactly as returned.',
        detail: { endpoint: 'GET /api/routing-profiles', rows: [['Response', '{ items: ["Profile 2542"] }']] },
      },
      {
        title: 'Place the order', tone: 'amber',
        text: 'Submit quantities per rate center + NPA. A mismatch against the catalog is rejected.',
        detail: {
          endpoint: 'POST /api/orders',
          rows: [
            ['Body', '{ profiles: [{ profile, requests: [...] }] }'],
            ['Response', '201 { result: { order number } }'],
          ],
        },
      },
      {
        title: 'Poll the status', tone: 'teal',
        text: 'Repeat until the order reaches a terminal state.',
        detail: {
          endpoint: 'GET /api/orders/{id}/status',
          rows: [['Statuses', 'Processing · Approved · Completed · Rejected']],
        },
      },
      {
        title: 'Collect the numbers', tone: 'red',
        text: 'Once Completed, read the DIDs that were provisioned to you.',
        detail: {
          endpoint: 'GET /api/orders/{id}/details',
          rows: [['Requires', 'status = Completed, else 409 (531)']],
        },
      },
    ],
    notes: [
      'Every request carries X-EDID-Username and X-EDID-Password, or HTTP Basic auth.',
      'The console is test-only. Live traffic needs X-EDID-Env: production with production credentials.',
      'Rate center and NPA must match /api/catalog exactly — mismatches return 595 / 596.',
    ],
  },

  'lnp-enterprise': {
    title: 'Porting numbers in (PON lifecycle)',
    subtitle: 'Create a porting request, correct it if the losing carrier rejects, activate on the due date.',
    steps: [
      {
        title: 'Check portability', tone: 'blue',
        text: 'Confirm the NPA-NXX can port at all before building a request.',
        detail: {
          endpoint: 'GET /api/lnp/portability/{npanxx}',
          rows: [['Response', '1 portable · 0 not yet open · -1 no']],
        },
      },
      {
        title: 'Pick routing', tone: 'green',
        text: 'Choose the profile id that will carry calls for the ported numbers.',
        detail: { endpoint: 'GET /api/lnp/routing-profiles', rows: [['Response', '[{ id, label, format }]']] },
      },
      {
        title: 'Create the PON', tone: 'purple',
        text: 'Submit end-user details and the numbers. The request goes to the losing carrier.',
        detail: {
          endpoint: 'POST /api/lnp/pons',
          rows: [['Body', '{ pon_data: {…}, routing: {…} }'], ['Response', '201 { pon, last_processstatus }']],
        },
      },
      {
        title: 'Watch the status', tone: 'amber',
        text: 'Poll the PON. On rejection, status_reason carries the reasons to fix.',
        detail: {
          endpoint: 'GET /api/lnp/pons/{pon}',
          rows: [['Statuses', 'New · Pending · Processed · Confirmed · Closed']],
        },
      },
      {
        title: 'Correct and resubmit', tone: 'teal',
        text: 'Only if rejected: fix the details and send the request again.',
        detail: {
          endpoint: 'POST /api/lnp/pons/{pon}/edit',
          rows: [['Requires', 'status = "Rejected. Pending Update"']],
        },
      },
      {
        title: 'Activate', tone: 'red',
        text: 'On the confirmed due date, port the numbers across. This is the irreversible step.',
        detail: {
          endpoint: 'POST /api/lnp/pons/{pon}/activate',
          rows: [['Requires', 'status = Confirmed'], ['Response', 'true']],
        },
      },
    ],
    notes: [
      'Same Espresso credentials as the DID product; LNP runs on the v4 endpoint.',
      'On the sandbox, POST /api/lnp/pons/{pon}/status forces a status so you can walk the whole flow without a losing carrier.',
      'A PON covers one number or a contiguous range — use service_details for several ranges.',
    ],
  },

  provisioning: {
    title: 'Provisioning a trunk with uBoss',
    subtitle: 'Submit a provisioning job, follow it to completion, then send the customer their welcome letter.',
    steps: [
      {
        title: 'Submit the job', tone: 'blue',
        text: 'Create a trunk provisioning request for the account.',
        detail: { endpoint: 'POST /uboss-robot/trunk-provisioning', rows: [['Response', '{ id, status }']] },
      },
      {
        title: 'Follow the status', tone: 'green',
        text: 'Poll until the robot finishes the job.',
        detail: { endpoint: 'GET /uboss-robot/trunk-provisioning/{id}/status', rows: [['Response', '{ status }']] },
      },
      {
        title: 'Review the record', tone: 'purple',
        text: 'Read one job, or list everything provisioned so far.',
        detail: {
          endpoint: 'GET /uboss-robot/trunk-provisioning',
          rows: [['All jobs', 'GET /uboss-robot/all-trunk-provisioning']],
        },
      },
      {
        title: 'Send the welcome letter', tone: 'amber',
        text: 'Email the customer their provisioning details once the trunk is live.',
        detail: {
          endpoint: 'POST /uboss-robot/email/{id}',
          rows: [['PDF', 'GET /uboss-robot/email/{id}/welcome-letter.pdf']],
        },
      },
    ],
    notes: [
      'Authenticate with your IristelX API key in the x-api-key header.',
      'GET /uboss-robot/email/welcome-letters lists the provisioning records that already have an email on file.',
    ],
  },

  e911: {
    title: 'Keeping a 911 listing correct',
    subtitle: 'Register the address dispatch will see, verify it, and keep it current.',
    steps: [
      {
        title: 'Add the listing', tone: 'blue',
        text: 'Register the subscriber address against the telephone number.',
        detail: {
          endpoint: 'POST /911-info?code={accountCode}',
          rows: [['Body', '{ id, first_name, street_address, city, … }']],
        },
      },
      {
        title: 'Verify it', tone: 'green',
        text: 'Read the listing back and confirm every field is what dispatch should receive.',
        detail: { endpoint: 'GET /911-info?code={code}&number={tn}', rows: [['Response', '{ data: { … } }']] },
      },
      {
        title: 'Keep it current', tone: 'amber',
        text: 'Whenever the subscriber moves, update the record the same day.',
        detail: { endpoint: 'PUT /911-info?code={accountCode}', rows: [['Body', 'full listing object']] },
      },
      {
        title: 'Remove on churn', tone: 'red',
        text: 'Delete the listing when the number is no longer in service.',
        detail: { endpoint: 'DELETE /911-info?code={code}&number={tn}', rows: [['Response', '{ data: "Success" }']] },
      },
    ],
    notes: [
      'These are live emergency records — a wrong address here is what emergency dispatch sees on a real 911 call.',
      'The API can answer HTTP 200 on failure, with the detail in an errors array or a null data field. Check the body, not just the status.',
      'For many listings at once, upload a CSV where each row carries its own OperationType (A / U / D).',
    ],
  },

  'lnp-wireless': {
    title: 'Wireless port-in, request to activation',
    subtitle: 'Create the port request, work the partner response, supplement it if anything changes.',
    steps: [
      {
        title: 'Check the gateway', tone: 'blue',
        text: 'Confirm the WLNP service is reachable and its database is up before you submit anything.',
        detail: { endpoint: 'GET /api/wlnp/api/health', rows: [['Response', '{ status: "ok" }']] },
      },
      {
        title: 'Submit the port in', tone: 'green',
        text: 'Send the WPR. The API builds the CWNPG XML and puts it on IBM MQ for the losing carrier.',
        detail: {
          endpoint: 'POST /api/wlnp/workflow/portin/submit',
          rows: [['Body', '{ onsp, desiredDueAt, lines[…] }'], ['Response', '{ reqNo, verIdReq }']],
        },
      },
      {
        title: 'Track the request', tone: 'purple',
        text: 'Find it in the Port Selection grid, then open the full detail by request number.',
        detail: {
          endpoint: 'GET /api/wlnp/api/port-selection',
          rows: [['Detail', 'GET /api/wlnp/api/port-details?requestNumber=']],
        },
      },
      {
        title: 'Read the response', tone: 'amber',
        text: 'The old carrier confirms, delays, or asks for resolution. Delays and rejections carry a code.',
        detail: { endpoint: 'Inbound via Watcher', rows: [['Delay codes', '6G · 6H · 6J · 6L · 8J']] },
      },
      {
        title: 'Supplement if needed', tone: 'teal',
        text: 'Change the date, correct details, or cancel — three different supplements, not one.',
        detail: {
          endpoint: 'POST …/portin/change-due-date/submit',
          rows: [['Modify', 'SUP=3, remarks required'], ['Cancel', 'SUP=1']],
        },
      },
      {
        title: 'Check for fallout', tone: 'red',
        text: 'If a request goes quiet, look for MPE fallout before assuming the API is at fault.',
        detail: { endpoint: 'GET /api/wlnp/api/icp-soa-errors', rows: [['Filter', 'RequestNumber']] },
      },
    ],
    notes: [
      'Requests are proxied through the gateway, so you only ever use this base URL — the WLNP service itself is on a private network.',
      'A request with chc=Y cannot also set autoAct=Y; the pair is rejected.',
      'Port Out reverses ownership: you supply the NEW local / reseller / network, and your home SPID is the OLD network.',
      'If inbound messages never arrive, check the Watcher logs and MQ archives before suspecting the API.',
    ],
  },

  'iristelx-accounts': {
    title: 'Standing up a subscriber',
    subtitle: 'Create the master account, attach a service, then manage the plan and features on it.',
    steps: [
      {
        title: 'Validate the address', tone: 'blue',
        text: 'Look the address up first so the account is created with a real, deliverable one.',
        detail: {
          endpoint: 'GET /canada-post/find',
          rows: [['Full address', 'GET /canada-post/retrieve']],
        },
      },
      {
        title: 'Create the account', tone: 'green',
        text: 'The master account is the billing entity. Everything else hangs off it.',
        detail: { endpoint: 'POST /accounts', rows: [['Response', '{ accountId }']] },
      },
      {
        title: 'Choose a plan', tone: 'purple',
        text: 'List the plans available to you before attaching a service.',
        detail: { endpoint: 'GET /plans', rows: [['One plan', 'GET /plans/{planCode}']] },
      },
      {
        title: 'Add the service', tone: 'amber',
        text: 'A service account is the actual line. One master account can hold many.',
        detail: {
          endpoint: 'POST /accounts/{accountId}/services',
          rows: [['List', 'GET /accounts/{accountId}/services']],
        },
      },
      {
        title: 'Configure features', tone: 'teal',
        text: 'Voicemail, call forwarding, SMS choice and the account PIN are all set per service.',
        detail: {
          endpoint: 'PATCH …/services/{serviceId}/voicemail',
          rows: [['PIN', 'POST /accounts/createPin/{accountId}']],
        },
      },
      {
        title: 'Audit and monitor', tone: 'red',
        text: 'Usage and the change journal tell you what happened and who changed it.',
        detail: {
          endpoint: 'GET …/services/{serviceId}/usage',
          rows: [['Journal', 'GET /accounts/{accountId}/log']],
        },
      },
    ],
    notes: [
      'Authenticate with your IristelX API key in the x-api-key header.',
      'Account-level changes use PATCH, not PUT — send only the fields you are changing.',
      'Deleting a service is permanent; the account journal is the only record of it afterwards.',
    ],
  },

  'iristelx-sim': {
    title: 'From SIM inventory to an active line',
    subtitle: 'Find a SIM, hold it, attach it to a service — or issue an eSIM instead.',
    steps: [
      {
        title: 'Find a SIM', tone: 'blue',
        text: 'Look up inventory by ICCID, IMSI or PUK. An assigned SIM returns the service it belongs to.',
        detail: {
          endpoint: 'GET /sim-cards',
          rows: [['One SIM', 'GET /sim-cards/{iccid}'], ['Filters', 'iccid · imsi · puk']],
        },
      },
      {
        title: 'Reserve it', tone: 'green',
        text: 'Hold the SIM against a sales account so nobody else can take it while you finish the order.',
        detail: {
          endpoint: 'POST /sim-cards/{sacode}/reserve',
          rows: [['Release', 'PUT /sim-cards/{sacode}/unreserve']],
        },
      },
      {
        title: 'Book it', tone: 'purple',
        text: 'Booking commits the reserved SIM to the order.',
        detail: { endpoint: 'POST /sim-cards/booked', rows: [['Then', 'attach to a service']] },
      },
      {
        title: 'Attach to the line', tone: 'amber',
        text: 'Point the service at the SIM, the handset and the telephone number.',
        detail: {
          endpoint: 'PATCH …/services/{serviceId}/sim',
          rows: [['Handset', '…/imei'], ['Number', '…/telephone-number']],
        },
      },
      {
        title: 'Or issue an eSIM', tone: 'teal',
        text: 'For eSIM, assign the profile instead of shipping plastic. The QR comes from the Mobile API.',
        detail: {
          endpoint: 'PUT /esim-cards/{iccid}/assign',
          rows: [['Inventory', 'GET /esim-cards'], ['QR', 'GET /mobile/esim/qrcode/local']],
        },
      },
    ],
    notes: [
      'Reserve before you book — booking an unreserved SIM risks losing it to another order mid-flow.',
      'Swapping a handset is an IMEI update on the service, not a new SIM.',
      'Deleting a SIM card removes it from inventory; it does not deactivate a line that is already using it.',
    ],
  },

  'iristelx-addon': {
    title: 'Managing add-ons on a service',
    subtitle: 'Read what is attached, add a package, adjust it later.',
    steps: [
      {
        title: 'Read what is there', tone: 'blue',
        text: 'Check the add-ons already on the service before attaching another.',
        detail: {
          endpoint: 'GET /accounts/{master}/services/{service}/add-on',
          rows: [['Keys', 'masterAccountCode + serviceAccountCode']],
        },
      },
      {
        title: 'Attach an add-on', tone: 'green',
        text: 'Add the package to the service. It takes effect against that service account only.',
        detail: { endpoint: 'POST /accounts/{master}/services/{service}/add-on', rows: [['Body', '{ add-on details }']] },
      },
      {
        title: 'Adjust it', tone: 'amber',
        text: 'Update the existing add-on rather than removing and re-adding it.',
        detail: { endpoint: 'PUT /accounts/{master}/services/{service}/add-on', rows: [['Method', 'PUT, full object']] },
      },
    ],
    notes: [
      'These routes key off the master account code and service account code — not the numeric account id used elsewhere.',
      'Add-ons are billed against the service they are attached to, so confirm the right service account before posting.',
    ],
  },

  'iristelx-commission': {
    title: 'Reading agent commissions',
    subtitle: 'Start broad across all agents, then drill into one agent over a date range.',
    steps: [
      {
        title: 'All agents', tone: 'blue',
        text: 'Start with the summary across every agent to see who has activity.',
        detail: { endpoint: 'GET /commission/agents', rows: [['Response', 'summary per agent']] },
      },
      {
        title: 'One agent, one period', tone: 'green',
        text: 'Drill into a single agent between two dates for the detail behind the summary.',
        detail: {
          endpoint: 'GET /commission/{agentId}/{startDate}/{endDate}',
          rows: [['Dates', 'in the path, not the query string']],
        },
      },
      {
        title: 'Commission records', tone: 'purple',
        text: 'The flat commission list for reconciliation against your own records.',
        detail: { endpoint: 'GET /agent-commissions', rows: [['Use', 'reconciliation']] },
      },
    ],
    notes: [
      'Start and end dates are path segments here, which is unusual for this API — a query string will 404.',
      'Your API key scopes what you can see: an agent key returns only that agent.',
    ],
  },

  'iristelx-bot': {
    title: 'Taking a bot payment',
    subtitle: 'A single call that charges an account on behalf of an automated assistant.',
    steps: [
      {
        title: 'Identify the account', tone: 'blue',
        text: 'The account id in the path decides who is charged.',
        detail: { endpoint: 'POST /bot/{accountId}/payment', rows: [['Path', 'accountId']] },
      },
      {
        title: 'Send the payment', tone: 'green',
        text: 'Pass a stored card token where you can, rather than raw card numbers.',
        detail: { endpoint: 'Body', rows: [['Card', '{ creditCard: { token } }'], ['Amount', 'amount + currency']] },
      },
      {
        title: 'Confirm the outcome', tone: 'amber',
        text: 'Read the response body — do not treat HTTP 200 alone as a successful charge.',
        detail: { endpoint: 'Response', rows: [['Check', 'errors[] before confirming']] },
      },
    ],
    notes: [
      'This charges real money. Test against a non-production account before wiring it to a live assistant.',
      'Prefer the card token over a raw card number so card data never passes through your own systems.',
      'Retrying a timed-out payment can double-charge — confirm the first attempt before sending another.',
    ],
  },

  'iristelx-mobile': {
    title: 'Calling the IristelX API',
    subtitle: 'Every IristelX product uses the same key-based authentication.',
    steps: [
      {
        title: 'Get a key', tone: 'blue',
        text: 'Iristel issues an API key per account. The key decides what data you can see and change.',
        detail: { endpoint: 'Issued by Iristel', rows: [['Scope', 'per account']] },
      },
      {
        title: 'Send it on every call', tone: 'green',
        text: 'Pass the key as x-api-key. The ReadMe docs say iristelx-api-key, but the live API accepts x-api-key.',
        detail: { endpoint: 'Header', rows: [['x-api-key', 'YOUR_API_KEY']] },
      },
      {
        title: 'Call the endpoint', tone: 'purple',
        text: 'Base URL is the same for every IristelX product.',
        detail: { endpoint: 'https://api.iristelx.com', rows: [['Example', 'GET /mobile/my-plan']] },
      },
      {
        title: 'Handle the response', tone: 'teal',
        text: 'Read the body, not just the status code — some routes report failures inside a 200.',
        detail: { endpoint: 'Response', rows: [['Check', 'errors[] and null data']] },
      },
    ],
    notes: [
      'In the console, paste your key into the API key box in the header bar. It is stored only in your browser and sent straight to api.iristelx.com — it never reaches the marketplace gateway.',
      'The same key works across Accounts, SIM, Numbers, Add-ons, Commissions, Mobile and Bot.',
    ],
  },
};

module.exports = FLOWS;
