'use strict';

/**
 * Product registry.
 *
 * Each product is one entry in the marketplace menu and owns a catalog of
 * endpoints. The page (docs + console) is generic: it renders whichever
 * product is selected, so adding a product means adding a file here.
 *
 * `classification` is the data-classification label shown on each product:
 * one of `public`, `internal`, `customer-confidential` or `restricted`.
 * Nothing is gated yet — that comes once every API is in place.
 */

const CLASSIFICATIONS = ['public', 'internal', 'customer-confidential', 'restricted'];

const PRODUCTS = [
  {
    id: 'provisioning',
    name: 'Provisioning (uBoss)',
    summary: 'uBoss robot: trunk provisioning jobs, their status, and welcome-letter emails.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./iristelx/uboss.json'),
  },
  {
    id: 'dids',
    name: 'Phone Numbers (DIDs)',
    summary: 'Search, order and manage DIDs from the Espresso catalog.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./dids'),
  },
  {
    id: 'lnp-enterprise',
    name: 'Number Porting — Enterprise (LNP)',
    summary: 'Wireline porting requests (PONs): create, correct, track, activate.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./lnp-enterprise'),
  },
  {
    id: 'lnp-wireless',
    name: 'Number Porting — Wireless (WLNP)',
    summary: 'Canadian wireless number portability (CWNPG / Syniverse ICP) workflows.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./lnp-wireless'),
  },
  // ---- IristelX (api.iristelx.com, iristelx-api-key auth) ----------------
  // Generated by scripts/import-iristelx.js from https://iristel-x.readme.io —
  // re-run that script to refresh; do not hand-edit the JSON files.
  {
    id: 'iristelx-accounts',
    name: 'IristelX · Accounts & Services',
    summary: 'Master accounts, service accounts, plans, add-ons and usage on the IristelX platform.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./iristelx/accounts.json'),
  },
  {
    id: 'iristelx-sim',
    name: 'IristelX · SIM & eSIM',
    summary: 'SIM card inventory, booking and reservation, eSIM provisioning and QR retrieval.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./iristelx/sim.json'),
  },
  // iristelx-addon and iristelx-bot are intentionally unregistered — not
  // exposed on the marketplace (catalog json files kept on disk).
  {
    id: 'iristelx-commission',
    name: 'IristelX · Commissions',
    summary: 'Agent commission summaries and per-agent commission detail by date range.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./iristelx/commission.json'),
  },
  {
    id: 'iristelx-mobile',
    name: 'IristelX · Mobile App',
    summary: 'Endpoints behind the subscriber mobile app: plans, usage, eSIM QR codes, port-in, notifications and support tickets.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./iristelx/mobile.json'),
  },
  {
    id: 'e911',
    name: '911 & E911',
    summary: 'Emergency service listings: add, retrieve, update, delete, bulk upload.',
    classification: 'customer-confidential',
    status: 'live',
    endpoints: require('./e911'),
  },
];

// Attach the hand-authored flow diagrams. Kept out of the product literals
// above so the generated catalogs and the authored docs stay separate.
const FLOWS = require('./flows');
for (const p of PRODUCTS) {
  if (FLOWS[p.id]) p.flow = FLOWS[p.id];
}

module.exports = { CLASSIFICATIONS, PRODUCTS };
