'use strict';

/**
 * Product registry.
 *
 * Each product is one entry in the marketplace menu and owns a catalog of
 * endpoints. The page (docs + console) is generic: it renders whichever
 * product is selected, so adding a product means adding a file here.
 *
 * `tiers` lists the partner types a product is intended for. The portal reads
 * `partnerType` from its cookie and the page shows the badge, but NOTHING is
 * gated yet — that comes once every API is in place.
 */

const TIERS = ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'];

const PRODUCTS = [
  {
    id: 'provisioning',
    name: 'Provisioning (uBoss)',
    summary: 'uBoss robot: trunk provisioning jobs, their status, and welcome-letter emails.',
    tiers: ['internal', 'agent', 'reseller'],
    status: 'live',
    endpoints: require('./iristelx/uboss.json'),
  },
  {
    id: 'dids',
    name: 'Phone Numbers (DIDs)',
    summary: 'Search, order and manage DIDs from the Espresso catalog.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./dids'),
  },
  {
    id: 'lnp-enterprise',
    name: 'Number Porting — Enterprise (LNP)',
    summary: 'Wireline porting requests (PONs): create, correct, track, activate.',
    tiers: ['internal', 'agent', 'reseller'],
    status: 'live',
    endpoints: require('./lnp-enterprise'),
  },
  {
    id: 'lnp-wireless',
    name: 'Number Porting — Wireless (WLNP)',
    summary: 'Canadian wireless number portability (CWNPG / Syniverse ICP) workflows.',
    tiers: ['internal'],
    status: 'live',
    endpoints: require('./lnp-wireless'),
  },
  // ---- IristelX (api.iristelx.com, iristelx-api-key auth) ----------------
  // Generated by scripts/import-iristelx.js from https://iristel-x.readme.io —
  // re-run that script to refresh; do not hand-edit the JSON files.
  {
    id: 'iristelx-accounts',
    name: 'IristelX · Accounts & Services',
    summary: 'Master accounts, service accounts, plans, add-ons and usage on the IristelX platform.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./iristelx/accounts.json'),
  },
  {
    id: 'iristelx-sim',
    name: 'IristelX · SIM & eSIM',
    summary: 'SIM card inventory, booking and reservation, eSIM provisioning and QR retrieval.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./iristelx/sim.json'),
  },
  {
    id: 'iristelx-addon',
    name: 'IristelX · Add-ons',
    summary: 'Add, update and read add-ons on a service account.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./iristelx/addon.json'),
  },
  {
    id: 'iristelx-commission',
    name: 'IristelX · Commissions',
    summary: 'Agent commission summaries and per-agent commission detail by date range.',
    tiers: ['internal', 'agent'],
    status: 'live',
    endpoints: require('./iristelx/commission.json'),
  },
  {
    id: 'iristelx-mobile',
    name: 'IristelX · Mobile App',
    summary: 'Endpoints behind the subscriber mobile app: plans, usage, eSIM QR codes, port-in, notifications and support tickets.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./iristelx/mobile.json'),
  },
  {
    id: 'iristelx-bot',
    name: 'IristelX · Bot',
    summary: 'Bot-initiated payment against an account.',
    tiers: ['internal', 'agent'],
    status: 'live',
    endpoints: require('./iristelx/bot.json'),
  },
  {
    id: 'e911',
    name: '911 & E911',
    summary: 'Emergency service listings: add, retrieve, update, delete, bulk upload.',
    tiers: ['internal', 'agent', 'reseller', 'cobranded', 'whitelabel'],
    status: 'live',
    endpoints: require('./e911'),
  },
];

// Attach the hand-authored flow diagrams. Kept out of the product literals
// above so the generated catalogs and the authored docs stay separate.
const FLOWS = require('./flows');
for (const p of PRODUCTS) {
  if (FLOWS[p.id]) p.flow = FLOWS[p.id];
}

module.exports = { TIERS, PRODUCTS };
